Pages
mansipadgelwar/Midori_E_Commerce_App pull request #2
Opened 2022-03-27 09:26 UTC by mansipadgelwar

Add pages for Ecomm App
Pages added:
1. Home Page
2. Product Listing Page
3. My Wishlist
4. My Cart

2022-03-27 11:03 UTC, manish591 requested changes
Your code is clean and readable also, 
I saw you are importing Header on every page instead you can import it inside app.js and put it above all the routers so that it will be visible for all the pages.

2022-03-27 11:03 UTC, manish591 commented on src/pages/Authentication/Login/Login.jsx
> +            <h3 className="h3">LOGIN</h3>
Don't give class names the same as elements.

2022-03-27 11:03 UTC, manish591 commented on src/pages/Authentication/Login/Login.jsx
> +            <label for="password" className="input-label">
Change `for` to `htmlFor`.

2022-03-31 05:04 UTC, manish591 approved these changes

2022-03-31 05:16 UTC, shilpe26 approved these changes
The file is easy to read as you applied prettier 👍
The file structuring is good
good to merge after seeing the suggestion given

2022-03-31 05:16 UTC, shilpe26 commented on src/components/VerticalCard/VerticalCard.js
> -        <img src="/images/Plant1.jpg" alt="plant" className="img-responsive" />
Good you have applied alt attribute to the images

2022-03-31 05:16 UTC, shilpe26 commented on src/pages/Authentication/Signup/Signup.jsx
> +              First Name:{" "}
remove these unwanted braces

2022-03-31 05:24 UTC, merged